// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaYKR-5CT8aOcWKzgaun1rSlYh-5cLzfo',
    appId: '1:258668634746:android:02b99ad75f6582887a91c3',
    messagingSenderId: '258668634746',
    projectId: 'cloud-anchors-d4a52',
    storageBucket: 'cloud-anchors-d4a52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHNK8FIhPFaoEYW_Hv_ty5MyjuePjLYIw',
    appId: '1:258668634746:ios:50dd29ed697e533b7a91c3',
    messagingSenderId: '258668634746',
    projectId: 'cloud-anchors-d4a52',
    storageBucket: 'cloud-anchors-d4a52.firebasestorage.app',
    androidClientId: '258668634746-rl3ru46gt22o97tv0hfn2n3vf5hk97k4.apps.googleusercontent.com',
    iosBundleId: 'name.vladhomenko.arFlutterPluginExample',
  );
}
